enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/roted_psyche_tree_only_black.png:
    name: roted_psyche_tree_only_black.png
    full_path: roted_psyche_tree_only_black.png
    type: image/png
    size: 33002
    path: user/themes/quark/images/logo/roted_psyche_tree_only_black.png
custom_logo_mobile: {  }
